@startuml
interface Пользователь {
авторизация()
показатьСписокЗаявок()
редактироватьЗаявку()
завершитьОбработкуЗаявки()
выход()
}
class Заказчик {
зарегистрироватьЗаявку()
согласитьсяНаПодключение()
отказатьсяОтЗаявки()
оплатитьЗаявку()
}
class ОператорКЦ {
зарегистрироватьЗаявку()
передатьЗаказчикуДокумент
}
class ОператорТО {
}
class ОператорМО {
}
class Тариф {
Наименование
Цена
}
class "Заявка на монтажные работы" as order
{
Идентификатор
Пользователь[] операторы Монтажного отдела
Отчет
Статус
Указания по монтажу
}

class "Заявка на подключение" as Заявка
{
Адреса подключения []
Тарифы подключения []
Оборудование []
Информация от Технического отдела
Статус
Статус оплаты
Пользователь Заказчик
Пользователь оператор Колл-Центра
Пользователь[] операторы Технического отдела
Заявка на монтажные работы
Документ на оплату
}

class "Документ на оплату" as paybill
{
Cписок стоимости оборудования
Стоимость установки
Суммарная стоимость
}
class Оборудование
{
    Наименование
    Цена
}

Заказчик --|> Пользователь
ОператорКЦ --|> Пользователь
ОператорТО --|> Пользователь
ОператорМО --|> Пользователь

Заявка o--> "1" ОператорКЦ
Заявка o--> "1..n" ОператорТО
order  o--> "1..n" ОператорМО
Заявка  o--> "1" Заказчик
Заявка  o-left-> "1" paybill
Заявка  o--> "1..n" Оборудование
Заявка <-left-o order
Тариф "1..n" <-right-o Заявка
@enduml