@startuml
interface Пользователь {
авторизация()
показатьСписокЗаявок()
редактироватьЗаявку()
завершитьОбработкуЗаявки()
выход()
}
class Заказчик {
зарегистрироватьЗаявку()
согласитьсяНаПодключение()
отказатьсяОтЗаявки()
оплатитьЗаявку()
}
class ОператорКЦ {
зарегистрироватьЗаявку()
передатьЗаказчикуДокумент
}
class ОператорТО {
}
class ОператорМО {
}
class Тариф {
Наименование
Цена
}
class "Адрес" as adr
{
Адрес
}
class "Заявка на монтажные работы" as order
{
Идентификатор
Пользователь оператор Монтажного отдела
Статус
Указания по монтажу
}

class "Заявка на подключение" as Заявка
{
Адрес подключения
Тарифподключения
Информация от Технического отдела
Статус
Статус оплаты
Пользователь Заказчик
Пользователь оператор Колл-Центра
Пользователь оператор Технического отдела
Заявка на монтажные работы
Документ на оплату
}

class "Документ на оплату" as paybill
{
Cписок стоимости оборудования
Стоимость установки
Суммарная стоимость
}

Заказчик --|> Пользователь
ОператорКЦ --|> Пользователь
ОператорТО --|> Пользователь
ОператорМО --|> Пользователь
Заявка "1" o-- "1" adr
Заявка "1" <-- "1" ОператорКЦ
Заявка "1" o-- "1" ОператорТО
order  "1" o-- "1" ОператорМО
Заявка  "1" <-- "1" Заказчик
Заявка "1" o-left- "1" paybill
Заявка "1" o-left- "*" order
Тариф "1" --right-o Заявка
@enduml