@startuml
'Заказчик'
skinparam dpi 180
actor Заказчик as A

participant "Заявка" as D

activate A
A -> D : Внесение адресов
A -> D : Внесение тарифов
A -> D : Создание
deactivate A

activate D
D --> A : Форма заявки, Документ на оплату
deactivate D


== Оплата ==
A -> D : Оплата заяввки на подключение

activate D
A <--D : Документ заявки на монтаж
deactivate D
activate A
A <-A : Контроль монтажа
A -> D : Закрытие заявки
deactivate A

activate D
D -> D : Закрытие заявки
D -> D : Архивация заявки
deactivate D
== Отказ ==
A -> D : Отказ оплаты
activate D
D -> D : Закрытие заявки
D -> D : Архивация заявки
deactivate D

@enduml
@startuml
'Оператор КЦ'
skinparam dpi 180
actor "Оператор КЦ" as A
participant "Заявка" as B
participant "Заявка на монтажные работы" as D
== Заявка на подключение ==

activate A
A->B : Принять заявку
A->B : Назначить оператора ТО
deactivate A

activate B
B --> A : Готовая заявка на подключение
deactivate B
activate A
A->B : Добавление документа на оплату
A->B : Закрытие заявки
deactivate A

== Заявка на монтажные работы ==


A->D : Создание заявки
activate A
A->D : Назначить оператора МО
deactivate A
D --> A : Форма заявки на подключение и монтаж
A -> D : Закрытие заявки
activate D
D -> D : Закрытие заявки
D -> D : Архивация заявки
deactivate D
@enduml

@enduml
@startuml
'Оператор ТО'
skinparam dpi 200
actor "Оператор ТО" as A
participant "Заявка на подключение" as B
A->B : Внесение информации об оборудовании
A->B : Закрытие заявки
@enduml

@enduml
@startuml
'Оператор МО'
skinparam dpi 200
actor "Оператор МО" as A
participant "Заявка на подключение" as B
A->B : Внесение информации об оборудовании
A->B : Закрытие заявки
@enduml