@startuml
'Заказчик'
skinparam dpi 180
actor Заказчик as A

participant "Система" as D
participant "Заявка на подключение" as B

A -> D : Создание заявки

D --> A : Форма заявки


A -> B : Внесение данных (тарифы, адреса)

A -> D : Регистрация заявки


...
A <-- D : Документ на оплату

== Оплата ==
A -> D : Закрытие заявки на подключение (оплата)
...

A <--D : Документ заявки на монтаж
A <-A : Контроль монтажа
A -> D : Закрытие заявки
D -> D : Закрытие заявки
D -> D : Архивация заявки
== Отказ ==
A -> D : Закрытие заявки на подключение (отказ)
D -> D : Закрытие заявки
D -> D : Архивация заявки


@enduml
@startuml
'Оператор КЦ'
skinparam dpi 180
actor "Оператор КЦ" as A
participant "Система" as D
participant "Заявка на подключение" as B
participant "Заявка на монтажные работы" as C
A->D : Выбор заявки


D --> A : Форма заявки на подключение

== Заявка на подключение ==
A->B : Назначение операторов ТО
A->D : Регистрация заявки на подключение

...
A<--D : Форма заявки на подключение
A->A : Проверка статуса(оплата, отказ)
A->D : Закрытие заявки
D->B : Смена статуса (закрыто)

== Заявка на монтажные работы ==
A->D : Выбор заявки
D --> A : Форма заявки на подключение
A->D : Регистрация заявки на монтаж
D --> A : Форма заявки на монтаж
A->C : Назначение операторов МО
...
A<--D : Документ заявки(Подключение, Монтаж)
A<-A : Проверка информации
A->D : Закрытие заявки
D->C : Смена статуса (закрыто)
D -> D : Закрытие заявки
D -> D : Архивация заявки
@enduml

@enduml
@startuml
'Оператор ТО'
skinparam dpi 180
actor "Оператор ТО" as A
participant "Система" as D
participant "Заявка на подключение" as B
A->D : Выбор заявки
D --> A : Форма заявки на подключение
A->B : Внесение информации об оборудовании
A->D : Закрытие заявки
D->B : Смена статуса (закрыто)
@enduml

@enduml
@startuml
'Оператор МО'
skinparam dpi 180
actor "Оператор МО" as A
participant "Система" as D
participant "Заявка на монтаж" as B
A->D : Выбор заявки
D --> A : Форма заявки на подключение
A->B : Внесение информации о монтаже
A->D : Закрытие заявки
D->B : Смена статуса (закрыто)
@enduml