@startuml
skinparam dpi 180
usecase 1
usecase 2
usecase 3
usecase 4
usecase 5
usecase 6

1 -> 2 : W12
2 -> 2 : W22
2 -down-> 6 : W26
4 -up-> 1 : W41
4 -right-> 6 :W46
4 -down-> 3 : W43
3 -right-> 5 : W35
5 -up-> 6 : W56
5 -> 5 : W55
5 -up-> 4 : W54
1 -> 6 : W16
6 .up-> 1 : 1/We
@enduml