@startuml
skinparam dpi 200
actor Заказчик as A

usecase uc3 as "Регистрация заявки на подключение"
usecase uc4 as "Внесение адресов"
usecase uc5 as "Оплата заявки"
usecase uc6 as "Отказ от заявки"
usecase uc7 as "Внесение тарифов"
A -down-> (uc3)
A -left-> (uc5)
A -left-> (uc6)
uc4 <.down. uc3 : include
uc7 <. uc3 : include
uc5 <. uc3 : extend
uc6 <. uc3 : extend
@enduml

@startuml
skinparam dpi 200
actor "Оператор КЦ" as A
usecase uc1 as "Регистрация заявки на подключение"
usecase uc2 as "Регистрация заявки на монтажные работы"
usecase uc3 as "Назначение операторов ТО"
usecase uc4 as "Назначение операторов МО"
usecase uc5 as "Закрытие заявки"
A -up-> (uc1)
A -down-> (uc2)
A -left-> (uc5)
uc1 .left.> uc2 : include
uc3 <.down. uc1 : include
uc4 <.down. uc2 : include
uc5 .up.> uc2 : include
@enduml

@startuml
skinparam dpi 200
actor "Оператор ТО" as A
usecase uc1 as "Внесение информации об\n оборудовании и стоимости"
usecase uc2 as "Редактирование заявки"
usecase uc3 as "Завершение обработки"
A -right-> (uc2)
A -right-> (uc3)
uc2 .> uc1 : extend
uc1 <.down. uc3 : include
@enduml

@startuml
skinparam dpi 200
actor "Оператор МО" as A
usecase uc1 as "Внесение отчетности по монтажу"
usecase uc2 as "Редактирование заявки"
usecase uc3 as "Завершение обработки"
A -right-> (uc2)
A -right-> (uc3)
uc2 .> uc1 : extend
uc1 <.down. uc3 : include
@enduml