@startuml
skinparam dpi 200
actor Заказчик as A

usecase uc3 as "Регистрация заявки"
usecase uc4 as "Внесение адресов"
usecase uc5 as "Оплата заявки"
usecase uc6 as "Отказ от заявки"
usecase uc7 as "Внесение тарифов"
usecase uc8 as "Закрытие заявки"
usecase uc9 as "Оплата через\n старницу банка"
usecase uc10 as "Согласие на монтаж"
A -up-> (uc3)
A -right-> (uc5)
A -right-> (uc6)
A -down-> (uc8)
A -left->(uc10)
uc4 .down.> uc3 : include
uc7 .> uc3 : include
uc5 .> uc9 : extend
uc6 .> uc8 : include
uc5 .> uc8 : include
uc3 .down.> uc10 : include
uc5 .down.> uc6 : extend
@enduml

@startuml
skinparam dpi 200
actor "Оператор КЦ" as A
usecase uc1 as "Регистрация заявки"
usecase uc2 as "Регистрация заявки на работы"
usecase uc3 as "Назначение операторов ТО"
usecase uc4 as "Назначение операторов МО"
usecase uc5 as "Завершение обработки заявки"
usecase uc6 as "Завершение обработки заявки на\n  монтажные работы"
A -> (uc1)
A -left-> (uc5)
A -right-> (uc3)
A -left-> (uc4)
A -down-> (uc2)
A -up-> (uc6)

uc2 .> uc1 : include
uc4 .> uc1 : include
uc3 .> uc1 : include
uc5 .up.> uc1 : include
uc5 .up.> uc6 : include
@enduml

@startuml
skinparam dpi 200
actor "Оператор ТО" as A
usecase uc2 as "Внесение единиц\n оборудования и стоимости"
usecase uc4 as "Просмотр активных заявок"
usecase uc5 as "Редактирование заявки"
usecase uc6 as "Передача заявки в КЦ"
A -down-> (uc5)
A -left-> (uc4)
A -right-> (uc6)
uc4 .> uc5 : include
uc5 .> uc2 : extend
uc6 .down.> uc2 : include
@enduml

@startuml
skinparam dpi 200
actor "Оператор МО" as A
usecase uc4 as "Просмотр активных заявок"
usecase uc3 as "Редактирование заявки"
usecase uc5 as "Внесение информации о \n выполнении монтажных работ и подключения"
usecase uc6 as "Передача заявки в КЦ"
A -right-> (uc3)
A -up-> (uc6)
A -left-> (uc4)
uc4 .> uc5 : include
uc5 .right.> uc6 : include
uc3 .down.> uc5 : extend
@enduml